### ISSUE TITLE
Google.GoogleSingIn+SignInException was thrown

### ISSUE THREAD

**Issue by Epiczzor** [googlesamples/google-signin-unity#18]
I used only this package and the sample sign in to create a test  app, i followed all the instructions (without firebase, i have setup the config in google developer account itself) and ended up with the build. When i attempt to sign in, i am redirected to select my email address and after selection i get the following error on the status screen:

`'Google.GoogleSignIn+SignInException' was thrown`

Also after resolving i get this warning in the editor :

```
Found conflicting Android library google-signin-support

Assets/Plugins/Android/google-signin-support-1.0.2 (managed by the Android Resolver) conflicts with:
Assets/Plugins/Android/google-signin-support-1.0.2.aar

Your application is unlikely to build in the current state.
```

any inputs ?

My config:
Android
Unity 2017.3
Sign in Master 1.0.2

**Comment by s4relok** [comment]
+1

**Comment by s4relok** [comment]
Worked only few times, then again 'Google.GoogleSignIn+SignInException' was thrown

**Comment by wesley-crick** [comment]
I think I am getting a similar problem.  I setup the sample and created a project in firebase.  I have not included firebase yet. I made a change to the sample to give some better logging from adb.

When I click the **Sign In** button
```
C:\android_sdk\platform-tools>adb logcat -s SignInFragment
--------- beginning of main
--------- beginning of system
01-15 23:20:19.416 21588 21633 D SignInFragment: TokenFragment.configure called
01-15 23:20:19.416 21588 21633 D SignInFragment: AuthHelperFragment.authenticate called!
01-15 23:20:19.416 21588 21633 D SignInFragment: Using DEFAULT_SIGN_IN
01-15 23:20:19.423 21588 21633 D SignInFragment: Requesting IDToken  client: 000000000000-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
01-15 23:20:19.442 21588 21633 D SignInFragment:  Has connected == false
01-15 23:20:19.495 21588 21633 D SignInFragment: Done with processRequest!
```
Then when I click on my **Google Account**
```
01-15 23:20:25.670 21588 21588 D SignInFragment: onActivityResult: 9009 0
01-15 23:20:25.677 21588 21588 D SignInFragment: Calling nativeOnResult: handle: 3136813640, status: 10 acct: null
01-15 23:20:25.678 21588 21588 D SignInFragment: onResume called
01-15 23:20:25.678 21588 21588 D SignInFragment: State is now ready
```
In the **Status** text, from the app, it says:
```
Got Error: DeveloperError Exception of type 'Google.GoogleSignIn+SignInException' was thrown
```

I also tried the update @s4relok mentioned, to update the `webClientId` in the `SignInSample` Class, no luck.   I am better with native Android, than Unity, so I may try an Android approach to confirm my credentials are correct.  Suggestions?  Thanks!

**Comment by Epiczzor** [comment]
Resolved the Issue, had unnecessary spaces in the web client id i provided on the canvas.

**Comment by gjRsVKUmODL7** [comment]
@Epiczzor @s4relok can you export package unity and share it? I have tired with this issue.

**Comment by reddy36996** [comment]
I have only used this plugin with sample package. I've setup firebase account too. I tried building the apk without firebase and provided web client id as well. Now when i try to sign in, i get following error in status text:
Got Error: DeveloperError Exception of type 'Google.GoogleSignIn+SignInException' was thrown
Pls note that it worked twice just by selecting resolving client jars from menu. After that it again stopped working after making few changes, since then i'm not able to make it work.

**Comment by amsyary1** [comment]
I got the same error because I forgot to add SH1 fingerprint to my app in firebase.

**Comment by codemaker2015** [comment]
This might be because of wrong SHA1 key or release.keystore file.

Follow the below steps to resolve the issue.

- Open Publishing settings in Player settings and click on Keystore manager to generate a release keystore. 
- Go to the folder where the keystore is located and open a terminal.
- Run the keytool utility provided with Java to get the SHA-1 fingerprint of the certificate. You should get both the release and debug certificate fingerprints.
- To get the release certificate fingerprint:

```
keytool -list -v -alias <your-key-name> -keystore <path-to-production-keystore>
```
- To use google auth, you need to provide some additional information to finish setting up your project. Create a project in the Google console and specify your package name (Eg: com.google.samples.quickstart.signin) when prompted. You will also need to provide the SHA-1 hash of your signing certificate. 

https://developers.google.com/identity/sign-in/android/start

Demo project repository link: https://github.com/codemaker2015/google-signin-unity3d-demo

For more: 

- https://developers.google.com/android/guides/client-auth
- https://github.com/googlesamples/google-signin-unity
